.gitignore
README.md
root.tf
root_variables.tf

Initial setup for making use of the Terraform backend contained in the AWS management account.

Tk initial set up

---

Jenkinsfile

Jenkins file that runs Terraform build and deploy to selected environment
Environment is based on the GIT branch defaulting to intg environment if branch not recognized
Valid GIT branches: intg, staging, prod
Job will run Terraform plan and post to slack for manual confirmation that the Terraform plan should be applied

Add Jenkins pipeline to run Terraform

---

Jenkinsfile
README.md

Test Jenkins build to management account users give correct permissions

Test Jenkins build

---

Jenkinsfile
root.tf

Get TDR environment from local instead of root variable
Point intg account to master branch in Jenkins build

Fix environment variable

---

Jenkinsfile

Changed url in slack message to new Jenkins url
Mapped intg account number to master branch

Change url in slack message

---

modules/consignment-api/ecs.tf
modules/consignment-api/templates/consignment-api.json.tpl
modules/consignment-api/variables.tf
modules/keycloak/outputs.tf
root.tf

The url is taken from the keycloak module route53 config so this should
update if we change that.

Add the url for the auth server to the ECS task.

---

Jenkinsfile

Added stage param to build to bring into line with other builds
Removed use of git branch to retrieve account number

Add stage param to Jenkins build

---

root.tf

This includes the antivirus lambda, the quarantine bucket and the bucket to store the lambda function code.

Antivirus lambda

---

root.tf

Renamed the SNS dirty upload topic module to use underscores to be consistent with other modules

Add SQS queues for backend checks

---

root.tf

Requires: https://github.com/nationalarchives/tdr-terraform-modules/pull/54

Trigger AV lambda by EFS file download

---

modules/transfer-frontend/cognito.tf
modules/transfer-frontend/ecs.tf
modules/transfer-frontend/templates/frontend.json.tpl

This allows us to put it into a hidden field on the upload form which we
can then use to assume a role and get a token which won't expire for 12
hours.

Add cognito role to env vars

---

modules/keycloak/ecs.tf
modules/keycloak/ssm.tf
modules/keycloak/templates/keycloak.json.tpl

Depends on PR: https://github.com/nationalarchives/tdr-terraform-backend/pull/105
Parameters to support GovUk Notify as email service for Keycloak

Add GovUk Notify params

---

root.tf

We're now having a notification lambda in each environment so I've added
a lambda module for it here.

Add notification lambda.

---

root.tf

There are new policies in
https://github.com/nationalarchives/tdr-terraform-modules/pull/116
I'm calling them here.

Use the new sqs queue policies

---

root.tf

- Call the existing create db users lambda
- Add create bastion user lambda security group to the consignment api db inbound security group rules

Add bastion user lambda

---

modules/keycloak/ecs.tf
modules/keycloak/ssm.tf
modules/keycloak/templates/keycloak.json.tpl

Requires PR: https://github.com/nationalarchives/tdr-terraform-backend/pull/119

Tdr 1197 keycloak ssm param reporting client

---

Jenkinsfile
Jenkinsfile-check
README.md
modules/consignment-api/database.tf
modules/consignment-api/ecs.tf
modules/consignment-api/security.tf
modules/database-migrations/lambda.tf
modules/keycloak/database.tf
modules/keycloak/ecs.tf
modules/keycloak/flowlogs.tf
modules/keycloak/outputs.tf
modules/keycloak/security.tf
modules/keycloak/vpc.tf
modules/shared-vpc/flowlogs.tf
modules/shared-vpc/root.tf
modules/transfer-frontend/cognito.tf
modules/transfer-frontend/ecs.tf
modules/transfer-frontend/security.tf
root_locals.tf
root_provider.tf
versions.tf

Requires PR: https://github.com/nationalarchives/tdr-jenkinslib/pull/57

Upgrade terraform v13

---

Jenkinsfile

Requires PR: https://github.com/nationalarchives/tdr-terraform-modules/pull/127

Use tdr-terraform-modules 'main' branch

---

root.tf

I've added in the signed cookies API gateway resource and the lambda that will respond to requests from API gateway.

Add signed cookies API and lambda

---

root_keycloak.tf

The auth server deployment is broken because the cluster and service
names don't follow the pattern Jenkins expects.
To avoid taking Keycloak down, I've created a new service with the
correct names and attached it to the load balancer.
I'll then create another PR to remove the keycloak_new_cluster. Keycloak
will stay up because the load balancer will be pointing to this new
service as well.

Add a new ECS service using the original name.

---

Jenkinsfile
Jenkinsfile-check

Requires PRs:
- https://github.com/nationalarchives/tdr-jenkins/pull/285; and
- https://github.com/nationalarchives/tdr-terraform-modules/pull/159

Terraform version updated on default Terraform image

---

root_github.tf

I've changed the github actions so they don't need as many secrets and
so they don't have to run in the repository environment for the tests
which causes all sorts of noise on the pull request. I've updated the
API one and added in one for the front end so I can move that over to
github actions.

Add frontend environment and update consignment api

---

root_github.tf
templates/iam_policy/deploy_lambda_github_actions.json.tpl

I've added the lambda to the policy and add the ACCOUNT_NUMBER to the environment secrets.

Setup tdr-checksum for github actions

---

root_github.tf
templates/iam_policy/deploy_lambda_github_actions.json.tpl

- Add permission to invoke the db migrations lambda
- Add environments

permissions for migrations invoke

---

.github/workflows/apply.yml
root_github.tf

- Replace test branch with main
- Add auth server secrets.

Add auth server secrets

---

root_consignment_export.tf
root_github.tf
templates/ecs_tasks/consignment_export.json.tpl
templates/iam_policy/deploy_lambda_github_actions.json.tpl
templates/iam_policy/github_invoke_create_user_lambda_policy.json.tpl

There's no need to use the old ones as we can assume a role directly
into the target account rather than assuming a role from management.

Add policies to create bastion.

---

.github/workflows/apply.yml

Depends on https://github.com/nationalarchives/tdr-github-actions/pull/24

Use reusable workflow for apply

---

root.tf
root_github.tf
templates/iam_policy/deploy_lambda_github_actions.json.tpl

https://github.com/nationalarchives/tdr-terraform-modules/pull/187 will need to be merged so the has can be updated in this PR

Add signed cookies lambda

---

root.tf
root_github.tf
root_locals.tf
templates/iam_policy/deploy_lambda_github_actions.json.tpl

Tdr 2028 reporting

---

root.tf

This passes in the path to be used as an environment variable as part of
this ticket https://national-archives.atlassian.net/browse/TDR-2179

Pass in parameter store variable.

---

modules/shared-vpc/outputs.tf
modules/shared-vpc/root.tf
root.tf
templates/iam_role/shield_response_assume_role.json.tpl

- Add elastic IP arns.
- Add advanced shield, the role for the SRT and a bucket for other information
- Update terraform modules hash

TDR 1829 changes for advanced shield

---

root.tf
root_data.tf

Create a new SQS queue
Created ssm parameter containing tre-out arn 
There will be a seperate pr to pass in an additional variable (sns_topic_arns) with the value from the SSM parameter once tre allows our SQS subscribe to tre-out SNS)

TDR-2391 Create new SQS queue

---

root.tf

This creates a log group for the waf logs and adds it to the waf module.
The name has to be `aws-waf...` because of AWS rules.

Add waf logging and log group

---

root.tf
root_backend_checks.tf
templates/api_gateway/backend_checks.json.tpl

- Add backend checks api definition
- Add the backend checks API arn

add backend checks api

---

root.tf
root_backend_checks.tf
root_github.tf
root_locals.tf
templates/iam_policy/allow_iam_db_auth.json.tpl
templates/iam_policy/backend_check_policy.json.tpl
templates/iam_policy/deploy_lambda_github_actions.json.tpl
templates/iam_policy/lambda_av_policy.json.tpl
templates/iam_policy/lambda_s3_backend_checks_policy.json.tpl
templates/iam_policy/lambda_s3_policy.json.tpl
templates/step_function/backend_checks_definition.json.tpl

The lambdas now need extra permissions to read and write to the results
bucket. There was a few bits that needed tidying, mostly concurrency
bits which were left over from the old checks.

Changes for S3 results in backend checks

---

root_backend_checks.tf

This was set to 1 which only allows one to run at a time. This switches
it off.

Set reserved concurrency.

---

root_provider.tf

As per pen test recommendation

Add external id to config.

---

modules/consignment-api/outputs.tf
modules/consignment-api/security.tf
root.tf

This was flagged by the pen testers as unused. I missed this on the
first pass of deleting things but it can go now.

Remove the old db security group.

---

root_keycloak.tf

- Update the backup retention period for the Keycloak database
- Update modules hash

TDR-2962 Update backup retention period

---

.github/scripts/logs.py

I didn't notice this, it was picked up by someone else.

Missed a set-output command

---

modules/transfer-frontend/cloudwatch.tf
modules/transfer-frontend/ecs.tf
modules/transfer-frontend/templates/frontend.json.tpl

Update the ECS task to run the collector in the same service

TDR-3129 Add x-ray collector container

---

root.tf

Requires https://github.com/nationalarchives/tdr-terraform-modules/pull/250

TDR-3246 Create log group for stopped ecs tasks

---

.gitmodules
README.md

'da-terraform-configurations' hold cross account configuration which is needed for different services to interact with each other
This will be needed for the implementation of the new TRE architecture

Add 'da-terraform-configuration' as sub-module

---

root.tf
root_locals.tf

Requires PR: https://github.com/nationalarchives/tdr-terraform-modules/pull/263

Enable bucket key on judgment export bucket

---

root_backend_checks.tf

Tested with python to 3.9 in AWS and it's working fine

Upgrade python to 3.9 for yara_av_v2 lambda

---

modules/consignment-api/ecs.tf
modules/consignment-api/templates/consignment-api.json.tpl
modules/consignment-api/variables.tf
root.tf
root_locals.tf

requires: https://github.com/nationalarchives/da-terraform-configurations/pull/20/files

add reference_generator_limit environment variable to api ecs

---

root_locals.tf

To be deployed when TRE and FCL ready for testing on staging

Enable export bucket encryption on staging

---

root.tf
root_keycloak.tf
root_locals.tf

Needs https://github.com/nationalarchives/tdr-terraform-modules/pull/266

TDR-3505 Update RDS instance certificate

---

root.tf
root_data.tf
root_locals.tf

Requires PR: https://github.com/nationalarchives/tdr-terraform-modules/pull/270

Remove support for TRE architecture

---

modules/consignment-api/ecs.tf
modules/consignment-api/templates/consignment-api.json.tpl
modules/consignment-api/variables.tf
root.tf
root_locals.tf
root_ssm_parameters.tf

TDR-3702 add new reporting variable

---

modules/transfer-frontend/ecs.tf
modules/transfer-frontend/templates/frontend.json.tpl
modules/transfer-frontend/variables.tf
root.tf
root_draft_metadata.tf
root_locals.tf

Add `DRAFT_METADATA_S3_BUCKET_NAME` environment variable to the frontend ecs task

Add draft metadata bucket frontend environment variable

---

root_keycloak.tf

This reverts commit cb25ac57e6a0b8bbd985b6d52967585ddde5b669.

Revert "Bump keycloak CPU and memory"

---

root_locals.tf

Will update submodule hash after https://github.com/nationalarchives/tdr-terraform-modules/pull/278 is merged

TDRD-155 DDT access to TDR s3 standard export buckets

---

root_transfer_service.tf
templates/ecs_tasks/transfer_service.json.tpl
templates/iam_policy/transfer_service_ecs_execution_policy.json.tpl

Will replace with `da-terraform-modules` when available.

Transfer service ecs task

---

root_draft_metadata.tf
root_transfer_service.tf

SharePoint App will be connecting to staging for testing to avoid ip restrictions on intg

Deploy transfer service to staging

---

root_transfer_service.tf

Alb name is limited to 32 characters. For staging environment using 'transfer-service' takes the name over this limit.
Provide an abbreviated function name for staging to reduce the name size to within the 32 charcter limit.

Use abbreviated alb name for 'staging'

---

root_transfer_service.tf
templates/step_function/transfer_service_process_dataload.json.tpl

Requires PR: https://github.com/nationalarchives/tdr-terraform-backend/pull/279

Tdrsp 32 skeleton process metadata step function

---

modules/transfer-frontend/templates/draft_metadata_policy.json.tpl
root_encryption.tf
root_guard_duty.tf
templates/endpoint_policies/s3_endpoint_policy.json.tpl
templates/iam_policy/backend_check_policy.json.tpl
templates/iam_policy/consignment_export_task_policy.json.tpl
templates/iam_policy/draft_metadata_validator_lambda.json.tpl
templates/iam_policy/guard_duty_s3_malware_scan_assume_role_policy.json.tpl
templates/iam_policy/guard_duty_s3_malware_scan_policy.json.tpl
templates/iam_policy/lambda_av_policy.json.tpl
templates/iam_policy/lambda_s3_backend_checks_policy.json.tpl
templates/iam_policy/lambda_s3_only_policy.json.tpl
templates/iam_policy/lambda_s3_policy.json.tpl
templates/iam_policy/metadata_checks_policy.json.tpl
templates/s3/allow_read_access.json.tpl

Requires PR: https://github.com/nationalarchives/tdr-terraform-backend/pull/285

Roles and permissions for running Guard Duty s3 malware scan

---

root.tf
root_s3_object_lifecycle.tf

s3 modules sets rule by default, this causes conflict if create rule resource separately from the s3 module
Dynamically implement rules to avoid this

Use dynamic lifecycle rules

---

root_encryption.tf
root_s3_bucket_access.tf

tdr-draft-metadata
tdr-consignment-export
tdr-consignment-export-judgment
tdr-upload-files
tdr-upload-files-quarantine
tdr-export
tdr-export-judgment

TDRD-672 - Remove admin user access from s3 buckets for prod only

---

root_consignment_export.tf

- tested these resources on staging and handle export of a 5GB transfer
- this PR replicates resources on prod (leave intg with lower resources)

TDRD-159: increase export task resources on prod

---

root.tf

Deleting objects from export bucket causing issues for Data Services

Roll back export bucket lifecycle rules

---

modules/consignment-api/ecs.tf
modules/consignment-api/templates/ecs_assume_role_policy.json.tpl
modules/transfer-frontend/ecs.tf
root_consignment_export.tf
root_github.tf
root_keycloak.tf
root_transfer_service.tf
templates/iam_policy/ecs_assume_role_policy.json.tpl

TDRD-828 - Secure ECS task trust policies

---

modules/transfer-frontend/ecs.tf
modules/transfer-frontend/templates/frontend.json.tpl
modules/transfer-frontend/variables.tf
root.tf
root_locals.tf

requires this [PR](https://github.com/nationalarchives/tdr-transfer-frontend/pull/4659) to be merged first

Remove metadata feature access blocks

---

modules/shared-vpc/flowlogs.tf
modules/shared-vpc/root.tf
modules/shared-vpc/variables.tf

This is good to go.  Handcranked the changes it makes into int and plan shows no changes so safe to merge.

fix: Confused deputy for flow logs

---

root_transfer_service.tf
templates/iam_policy/aggregate_processing_lambda_policy.json.tpl

Skeleton resources for aggregate processing lambda

Skeleton resources for aggregate processing lambda

---

root_backend_checks.tf
root_locals.tf

waiting for https://github.com/nationalarchives/tdr-terraform-modules/pull/337

upgrade python

---

root.tf

Will update submodule hash after https://github.com/nationalarchives/tdr-terraform-modules/pull/341 is merged

Remove client secret from inactive keycloak lambda

---

root.tf
root_transfer_service.tf

Transfer service needs to send message to SQS queue encrypted with KMS key

Tranfer service KMS key permissions
