- modules/keycloak/loadbalancer.tf
This fixes some weird behaviour in terraform where it complains that the
target group isn't attached to any load balancer listeners.
> Add random string to target group.

- root.tf
Add new common tag that will let Digital Services identify TDR resources when they review the organisation's AWS bill.
> Add CostCentre tag to all resources

- Jenkinsfile
Switch Slack channel so that releases don't spam the main TDR channel.
> Post update messages to #tdr-releases Slack channel

- modules/keycloak/vpc.tf
- modules/shared-vpc/root.tf
AWS automatically creates a default security group with each VPC, which includes an inbound from any rule. It's not possible to delete this default security group. This change brings the default security group under Terraform management and removes all rules.
> remove rules from default security groups

- Jenkinsfile
Jenkins uses a new temporary directory for each stage so the folder
cloned in the first stage wasn't available for the plan stage. I've
moved the git clone into the plan stage.
> Move git clone into the set up stage.

- modules/transfer-frontend/outputs.tf
The front end dns name is blank so with the url as it was, we were
getting https://.tdr-integration.nationalarchives.gov.uk which doesn't
make sense. This removes it.
> Remove the prefix from the url.

- modules/keycloak/flowlogs.tf
This is because of an issue where the flow log cloudwatch log groups
were being recreated after terraform destroy was run. This prevented us
from running terraform apply because they already existed. This is
probably due to this github issue
https://github.com/hashicorp/terraform/issues/14750#issuecomment-303337513
The policy doesn't need to be able to create log groups because the log
group is created by terraform and removing this permission prevents it
recreating the log group after terraform destroy.
> Remove create log group permission.

- README.md
- root_provider.tf
Configure a specific version, so that we can be sure that we use the same AWS provider when deploying changes to each environment, rather than using the most recent one.
Upgrading the provider can cause problems that need to be fixed, such as new features that require new permissions to be granted to the Jenkins terraform role. Fixing the verison prevents us from hitting these kind of problems unexpectedly during a production deployment.
Also remove an old environment variable from the README.
> Set AWS provider version

- modules/consignment-api/templates/consignment-api.json.tpl
This will allow us to launch the ECS task with different config, depending on the environment.
The main reason for doing this now is to be able to set different CORS headers in integration vs staging and production, so that we can run a frontend dev environment that connects to the integration API.
https://national-archives.atlassian.net/browse/TDR-138
> Pass environment to API ECS task

- modules/keycloak/ecs.tf
- modules/keycloak/outputs.tf
- modules/keycloak/ssm.tf
- modules/keycloak/templates/keycloak.json.tpl
- modules/transfer-frontend/ecs.tf
- modules/transfer-frontend/templates/frontend.json.tpl
- modules/transfer-frontend/variables.tf
- root.tf
- root_provider.tf
Updating the database through the API with the backend checks data, requires authorisation via a keycloak service account, as backend checks triggerd by lambda, not a user
Keycloak service account authorisation requires additional secret to allow for retrieval of token by client id and client secret: https://www.keycloak.org/docs/latest/server_admin/index.html
Create and expose the backend checks secret to the relevant TDR modules to allow updating of the backend checks data via lambda
> Add keycloak backend checks secret

- modules/keycloak/ssm.tf
Prevent Terraform from regenerating Keycloak client secrets, because changing them breaks the integration between the client apps and the Keycloak server.
We will need to revisit this to find a way to safely refresh a secret without causing downtime.
> Ignore changes to Keycloak client secrets

- root.tf
- root_locals.tf
Enable cross-origin requests from the local dev host (localhost:9000) in the integration environment.
This will make it possible to do local development against the integration backend.
This change depends on https://github.com/nationalarchives/tdr-terraform-modules/pull/32
> Allow uploads to the intg dirty bucket from the local dev environment

- root.tf
- root_data.tf
Allows tdr-terraform-modules to be used in environments such as mgmt where this SSM parameter doesn't exist
> Fix SSM parameter issue in mgmt

- modules/database-migrations/lambda.tf
The execution role didn’t have permission to view the cloudwatch logs.
I’ve added the permission in but it still complains that you don’t have the permission
but if you run the migration lambda, the logs are available in cloudwatch
so this time, the message is wrong.
This is the message we get for all our lambdas and they log to cloudwatch
fine so this is just something wrong in the AWS console.
I suspect it needs * in the resources in the policy or we need to use
the AWS managed policy or something but we're not going to do either of
those things so we can safely ignore it.
> Add cloudwatch log group and permissions.

- Jenkinsfile
This fixes the broken Jenkins build.
Calls to external functions need to be wrapped in a `script`.
> Wrap call to Slack function in `script` block

- modules/keycloak/templates/keycloak.json.tpl
Each TDR environment has specific Keycloak configuration for some properties which differ across the TDR environments
Require the TDR environment to be available as environment variable to know which environment Keycloak docker image is being built in to apply the specific Keycloak configuration
> Make environment name available as environment variable

- Jenkinsfile
Whenever Jenkins posts a Terraform message in Slack, the link in broken due to the spaces in the job name. This PR replaces spaces with the percent encoding
> Replace space with percent encoding

- root_provider.tf
This gives us access to new EFS features, which we're planning to use in the file format checks.
> Upgrade the AWS provider to 2.69

- modules/keycloak/ecs.tf
- modules/keycloak/ssm.tf
- modules/keycloak/templates/keycloak.json.tpl
Additional Keycloak client added to TDR realm to allow for updating of realm using APIs
To make API calls using client credential to obtain access token. Therefore need a new client secret for the client.
> New Keycloak realm client secret

- modules/keycloak/ecs.tf
- modules/keycloak/ssm.tf
- modules/keycloak/templates/keycloak.json.tpl
Both Auth Server docker build and the Jenkins update environments require the keycloak configuration properties.
For both enviornment to access this value it should be set in the ssm parameters so it comes from a single source for both environments
> Add keycloak config properties ssm parameter

- modules/keycloak/database.tf
- modules/keycloak/security.tf
- modules/keycloak/templates/keycloak.json.tpl
- modules/keycloak/variables.tf
- root.tf
The version of mysql on aurora serverless was too old to work with the
latest version of keycloak properly.
We were also getting a lot of connection errors from keycloak which is
unrelated to the upgrade but still isn't great.
So I've moved keycloak to use standard postgres RDS which is the same DB
the consignment api uses so we're at least consistent now.
> Move keycloak to postgres

- root.tf
Requires: https://github.com/nationalarchives/tdr-terraform-modules/pull/50
EFS file system to be used by all backend checks
Rename resources to reflect use by all backend checks not just file format check
> Rename EFS file system

- modules/shared-vpc/root.tf
- modules/transfer-frontend/ecs.tf
- modules/transfer-frontend/templates/frontend.json.tpl
- modules/transfer-frontend/variables.tf
- root.tf
We need to add the trusted IP addresses to the play app so that the
https forwarding from the load balancer works properly.
The IPs that the load balancer uses are the private IPs of the network
interfaces. These are created by AWS when you create the load balancer
and can't be specified in terraform directly so I'm using the network
interface data to get the interfaces for both availability zones and
passing them to the play app via environment variables.
> Add alb network interface private IPs

- root.tf
This adds the rule to abort incomplete multipart uploads to the bucket.
> Add variable to use lifecycle rule.

- root.tf
The notification lambda will subscribe to this topic in each account so any messages sent to it will be sent to the notifications lambda. The arn for the topic is passed to the step function so it can send messages on success/failure of the export.
> Add notifications sns topic.

- modules/consignment-api/templates/consignment-api.json.tpl
- modules/keycloak/templates/keycloak.json.tpl
- modules/transfer-frontend/templates/frontend.json.tpl
The problem is that when a stack trace is logged, cloudwatch puts each trace line in its own event which is hard to read. This tells cloudwatch the format of the date to look for and will put any following lines in the same event until it gets to another date.
> Add an awslogs-datetime-format

- root.tf
- root_data.tf
The export task needs to talk to the keycloak admin url but that is hidden behind the WAF which has an IP whitelist. We need to add the NAT public IPs which is what the ECS tasks use to get to the internet, to the WAF.
> Add NAT public IP to WAF.

- root.tf
This is only used to determine whether we set version expiration which
is being removed so we don't need it.
> Remove version lifecycle parameter

- modules/consignment-api/database.tf
- modules/keycloak/database.tf
Either terraform or AWS is clever enough to know that if you want more than one instance in your cluster, the second on is a read replica. I've tested this and it is working.
> Add read replicas to keycloak and consignment api databases

- root.tf
The lambdas need to have their environment variables encrypted in transit using a KMS key. The encrypted environment variables are set using terraform and the lambda has to decrypt them. There are two steps to allow the lambda to decrypt the environment variables using KMS. The lambda execution policy needs permission to decrypt using the key and the key policy itself needs to allow the lambda to decrypt the files. Most of the changes are in https://github.com/nationalarchives/tdr-terraform-modules/pull/92 which should make this a bit clearer.
> Change KMS key policy and pass kms arn to lambdas

- modules/keycloak/outputs.tf
- root.tf
This sets the own_host_header_only value to true which sets the load balancer listener up as it is in https://github.com/nationalarchives/tdr-terraform-modules/pull/96.
Also, I'm outputting the auth domain as we only had it in https://domain/auth format before.
> Only allow host from keycloak

- modules/consignment-api/security.tf
- modules/consignment-api/variables.tf
- modules/keycloak/security.tf
- modules/keycloak/variables.tf
- modules/transfer-frontend/security.tf
- modules/transfer-frontend/variables.tf
- root.tf
- root_data.tf
- root_locals.tf
This changes where the list of IPs which are allowed to access Keycloak admin URLs is read from.
Before, we read the list from a parameter in the AWS SSM Parameter Store. Now, it reads the list from the tdr-configurations repo.
The tdr-configurations repo was already being used for the frontend load balancer allow list, so this change makes the WAF consistent with the frontend.
It also reduces the number of deployment steps. When the list changes, we can now deploy the changes by running this Terraform project, without having to deploy the change to the parameter store first.
Also rename "whitelist" to "allow list" to match the GOV.UK styleguide: https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#allow-list
> Fetch WAF allow list from tdr-configurations instead of SSM param

- root.tf
The default policy in tdr-terraform-modules is being changed, so this Terraform script now needs to specify the policy to use. The relevant policy is the one which allows SNS and SQS to use the KMS key.
See https://github.com/nationalarchives/tdr-terraform-modules/pull/102 for more about why the default is changing.
> Specify KMS policy for encryption key

- modules/consignment-api/outputs.tf
- modules/keycloak/outputs.tf
- root.tf
The create db users are now restricted to outbound access on 5432 to the database security group.
The lambdas which connect to EFS are limited to the EFS port to the EFS mount point security group.
All of them have a rule restricting access on 443 to all IPs. 
The api update and export authoriser wern't in the VPC so I've added them in.
> Restrict outbound security group access for lambdas

- modules/consignment-api/database.tf
- modules/keycloak/database.tf
Upgrade the consignment database and Keycloak database from version 11.6 to 11.9.
The databases have already been upgraded in all AWS environments, so this change just brings the Terraform in line with the deployed configuration.
> Upgrade Postgres databases to version 11.9

- root.tf
The domain variable isn't used in the alb module. The certificate configuration is done externally and passed in with the certificate arn.
> Remove domain variable.

- root.tf
This PR https://github.com/nationalarchives/tdr-transfer-frontend/pull/678 enables strict transport security. The load balancer requests are over http and they won't send the correct headers the load balancer does for requests from external clients that lets play treat it as http so you get a 308 response from any health check requests.
This isn't the only way to do it, we could have a dedicated healthcheck url in the play application and disable strict transport security for that url but this seems cleaner.
> Change health check expected code for frontend ALB

- root_locals.tf
Add `TerraformSource` tag which links to this code repo. This will make it easier for devs to find the Terraform source which created a particular resource in the AWS console.
> Add new default tag for Terraform source

- root.tf
- root_locals.tf
Set the SQS message visibility timeout to be three times the lambda timeout for each of the file check lambdas, including the file download and API update lambda.
This should prevent messages from being sent to the failure queue incorrectly. See ADR 20 for how this change works: nationalarchives/tdr-dev-documentation#122
This will make retries slower, because the message visibility timeout has to expire before a failed file check is retried. The plan is to add extra error handling to the file checks which sets the message visibility timeout to zero to cause the check to be retried immediately.
Marking as a draft PR until https://github.com/nationalarchives/tdr-terraform-modules/pull/124 is merged.
> Increase the message visibility timeout for file checks

- root.tf
There is a PR for terraform-modules
https://github.com/nationalarchives/tdr-terraform-modules/pull/130
which will need to be merged first.
There is a Jira ticket TDR-1242 which shows the results of testing
different values for reserved concurrency and 3 is about the best one.
> Set reserved concurrency to 3

- root.tf
This uses the `tdr-terraform-modules` athena module to create an athena workspace. There's a separate PR for that repo to add the queries in, this just adds them to the workspace. I've also added in the s3 bucket to store the query results.
> Add athena bucket, workspace and queries

- modules/consignment-api/security.tf
- root.tf
- Remove bastion security group. This is now created when the bastion is created and the rule to allow the security group to access EFS is now added in in the bastion terraform.
- Modify the export EFS policy to use specific IAM roles. This allows the backend checks and export roles to read and write and the bastion role to only read.
- Create the bastion role. This needs to always exist as you can't add a role to an EFS policy if it doesn't exist and you can't update an existing EFS policy in a separate terraform project. It has no policies attached to it though, these are attached in the bastion terraform so the role is useless until that is run.
> Remove bastion security group

- root.tf
The cloudwatch module at the moment only creates an origin access
identity which is needed to pass into the bucket policy.
I'll add in other resources to the Cloudwatch module later.
This needs
https://github.com/nationalarchives/tdr-terraform-modules/pull/140 to be
merged before this can be.
> Add s3 bucket and origin access identity.

- root.tf
This log bucket is for logging cloudfront requests so we want versioning
enabled but we don't need a log bucket for the log bucket.
> Add cloudfront distribution and log bucket.

- root.tf
If the auth server is slow to respond, this can take longer than 10
seconds so I've upped it to 60. It should never take this long unless
something is wrong.
> Change the lambda timeout.

- root.tf
- root_consignment_export.tf
- root_locals.tf
- templates/ecs_tasks/consignment_export.json.tpl
Move consignment export task.
This moves it over to using the new generic_ecs module.  When I tried to delete keycloak, I was getting a circular dependency problem on the export module and I think this is the way it's set up.
This should solve the problem and moves us closer towards having a properly generic terraform-modules.
> Move consignment export task

- root.tf
- root_data.tf
- root_locals.tf
This is a custom ACL grant which allows the aws logs delivery https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/AccessLogs.html#AccessLogsBucketAndFileOwnership
account to access the bucket which allows Cloudfront to write logs to it.
It also allows full access to the bucket owner so we can view and change the logs in it.
> Set canonical ids which are allowed full access.

- root_github.tf
* Remove the team slug to remove environment restrictions so e2e test
runs don't need to be approved.
* Don't create an environment for prod as we don't run the tests on
prod.
> Change e2e tests environment

- root_github.tf
We want the secrets to be on the repository rather than in a GitHub
environment. Environments are meant to be for deploying code so any PR
where the tests are running currently shows a lot of spam from GitHub
about a deployment starting.
We still need environment specific secrets but we're doing this by
prefixing them with the environment and adding them at the repository
level.
> Change e2e tests secrets.

- modules/consignment-api/database.tf
AWS has been upgrading the RDS databases in the background and now the
versions are out of sync with terraform.
This now matches the deployed version.
> Upgrade databases

- .github/workflows/apply.yml
We're not updating the release versions like the Jenkins job used to do
so we can't see when the terraform run is out of date.
> Update release versions.

- root_github.tf
These are needed so we can restrict prod and staging deployments which
we're not at the moment.
> Add environments for export job.

- templates/iam_policy/deploy_lambda_github_actions.json.tpl
This is the policy that allows us to deploy the lambdas. I was adding
them one at a time but I keep forgetting so I've added in all the
missing ones in one go.
> Add lambdas to GitHub policy

- root_github.tf
- templates/iam_policy/github_run_ecs_policy.json.tpl
The role needed by the file format run ECS task job is very similar to
the one for running the Keycloak update job so I've refactored the
keycloak one to work with both.
> Add file format roles and secrets.

- root_github.tf
I've set this to need approval from the TDR team in integration so not
everyone in TNA can set the service unavailable page.
> Add service unavailable environment.

- root.tf
Keycloak has changed from using auth/admin to just admin so the WAF
rules need to be updated.
> Update restricted URI.

- root_keycloak.tf
- templates/ecs_tasks/keycloak.json.tpl
This is needed when we start the service, it will read the value of the
secret from this environment variable.
> Add an environment variable for the rotate secrets client.

- modules/consignment-api/ecs.tf
- modules/consignment-api/variables.tf
- root.tf
- root_keycloak.tf
I wanted to move everything to a new larger subnet but it turns out
that is a lot more difficult than it sounds so for now, I've moved the
API and Keycloak ECS tasks to the backend-checks subnet.
This **should** be a temporary change. There is a ticket
https://national-archives.atlassian.net/browse/TDR-2253
to sort this properly.
> Move API and Keycloak to another subnet.

- modules/consignment-api/ecs.tf
- modules/consignment-api/outputs.tf
- modules/consignment-api/templates/allow_iam_db_auth.json.tpl
- modules/consignment-api/variables.tf
- root.tf
- root_keycloak.tf
- root_locals.tf
Add a new single instance database.
This does the following.
Creates a new single instance DB for keycloak and the API.
Updates the create-users lambdas with the new credentials. We don't use these lambdas normally so this is fine.
Update the task roles to allow access to the new databases.
Adds the existing keycloak master credentials to SSM as for some reason they're not there. These will be deleted after this is all deployed.
Once this is merged and deployed, I'll put in another PR to switch over the API and Keycloak to use these DBs.
This is a draft because it needs https://github.com/nationalarchives/tdr-terraform-modules/pull/204 to be merged so I can update the modules hash
> TDR 2222 single db instance

- modules/transfer-frontend/elasticache.tf
For versions above 6, you need to set the version as 6x rather than a
specific version.
This is the latest version which AWS offer despite there being a 7.0
available.
> Update redis version

- modules/consignment-api/ecs.tf
- modules/consignment-api/ssm.tf
- modules/consignment-api/templates/consignment-api.json.tpl
- root_keycloak.tf
- root_locals.tf
This depends on 
https://github.com/nationalarchives/tdr-terraform-environments/pull/249
https://github.com/nationalarchives/tdr-terraform-modules/pull/204
This will update the API and Keycloak ECS tasks to use the new database. This can only be deployed once the new databases have been created and migrated. The steps are defined in [this Jira ticket](https://national-archives.atlassian.net/browse/TDR-2222?focusedCommentId=27261)
> Move services to new db

- root_github.tf
The run report action needs to be run by users outside TDR. At the
moment, it's run in an environment which needs approvals.
I want to run it outside the environment but for this we need three
secrets, INTG_ACCOUNT_NUMBER, STAGING_ACCOUNT_NUMBER,
PROD_ACCOUNT_NUMBER which this sets.
> Use account specific parameter names.

- root_github.tf
- templates/iam_policy/github_e2e_test_secrets_policy.json.tpl
The e2e tests need to get the secrets from the parameter store as when
they're rotated, the hard coded ones in GitHub secrets don't update.
I've added a policy and role to allow it to get the two secrets it needs
and removed the secrets from the environment.
> Add policy for e2e tests.

- root_keycloak.tf
- templates/ecs_tasks/keycloak.json.tpl
- templates/iam_policy/keycloak_ecs_task_role_policy.json.tpl
Keycloak will retrieve the value of the GOV.UK Notify api key and template id directly from the ssm parameter instead of reading from an environment variable
This will mean any rotation of these values will not require code redeployments
This will support the rotation of the GOV.UK Notify api key
Once the value is being retrieved directly the existing corresponding secrets will be removed as environment variables
> Add ssm parameter path for Notify key and template id

- root.tf
- root_locals.tf
TRE SNS topics for other environments not currently configured and therefore cannot subcribe to non-existent SNS topics
When the TRE AWS infrastructure for other environments is in place, this should be updated to allow the subscriptions
> Only subscribe to TRE SNS topic in intg

- root_github.tf
The tdr-file-upload-data repo is replacing tdr-download-files. This adds
the ACCOUNT_NUMBER secret so we can deploy it.
> Add a new environment for the new repo

- .github/scripts/logs.py
If the plan log is over 262144 bytes, you can't send it in a single log
event. This checks the size and splits it in half if it's too big.
This should keep us going for a while, hopefully until we can split out
tdr-terraform-environments.
> Split large log files before sending to Cloudwatch

- root.tf
- templates/api_gateway/backend_checks.json.tpl
- templates/api_gateway/export_api.json.tpl
- templates/api_gateway/sign_cookies_api.json.tpl
- templates/iam_policy/assume_role_policy.json.tpl
- templates/iam_policy/export_api_policy.json.tpl
- templates/iam_policy/sign_cookies_api_policy.json.tpl
These have been moved from tdr-terraform-modules to make the module less
TDR specific and the call to the module has been updated to use the new
modules. This will have to be deployed in tandem with https://github.com/nationalarchives/tdr-terraform-modules/pull/236
If I move the resources using `terraform state mv` this shouldn't need
downtime.
> Move API gateway definitions and policies.

- root_backend_checks.tf
We had a timeout with it set to 15 seconds. This may need a bit of
tweaking but this should be enough for now.
Any longer and it takes too long to fail and it costs us more.
> Increase the lambda timeout to 60s.

- root_locals.tf
IAM user group is no longer needed as pen testing complete
Leaving an unsed IAM user group is considered a moderate secruity risk in itself
> Remove security audit IAM user group

- root_github.tf
- templates/iam_policy/github_run_e2e_tests_policy.json.tpl
For some reason we were assuming a role in GitHub actions in the
management account and then assuming a role into the integration or
staging accounts within the tests. This was necessary when we were
running it in Jenkins but it isn't any longer.
This is a new role which the e2e tests will assume in the actions
runner.
> Add new E2E test policy.

- root_consignment_export.tf
- root_github.tf
The module which contained the policy json has been deleted. This
updates it to use the json in this repo.
> Fix the assume role policy paths.

- root.tf
We don't need this and the pen test report flagged it.
> Remove the http listener for the frontend load balancer.

- templates/step_function/backend_checks_definition.json.tpl
This has been changed so we can tell when an individual file check has
failed for a particular file.
If there is an error with a file check, we send a message to the
notifications lambda and then add the name of the file check to the
error.
This is then aggreagated at the end of the map function so we should see
"failures": ["Antivirus"] for a particular file. We can use these to set
the file and consignment statuses when the backend checks fail.
This needs to be done first because the existing lambdas will ignore
this new field but it needs to be there before I can change the lambda
code.
I've also removed the general catch block around the map loop because
it's not necessary now we have individual catches on each of the checks
lambdas.
We may need to do some additional error handling on …
> Add lambda failure information to backend checks.

- root_backend_checks.tf
Lambda timeout was set to default to 15secs and was timing out for large consignments
Increase to 60secs to bring into line with other backend checks lambdas
> Increase api update lambda timeout

- .terraform.lock.hcl
- root_github.tf
Now that these repos are being used by other teams, the environments
need to be prefixed with the team name
> Update secrets for custodian and config repos.

- modules/transfer-frontend/ecs.tf
Allow logs to be inserted to the 'ecs-task-events' log group
> TDR-3295 Add 'ecs-task-events' log group permissions to frontend_ecs_execution role

- root_github.tf
Requires PR: https://github.com/nationalarchives/tdr-terraform-github/pull/4
Remove tdr-reporting and tdr-keycloak-user-management configurations as we have migrated to new tdr-terraform-github repo
> Remove tdr-reporting and tdr-keycloak-user-management configurationss

- root_locals.tf
TRE naming of environments does not following TDR's naming convention
Add local to convert the TDR environment name to the correct TRE environment name
> Local to set the correct tre environment name

- root.tf
Until actual event bus arn available use a placeholder value for Terraform to apply successfully
> Cipher text encrytion requires string value

- root.tf
Requires PRs:
- https://github.com/nationalarchives/tdr-terraform-environments/pull/378
- https://github.com/nationalarchives/tdr-terraform-environments/pull/380
In addition requires AWS SSO TDR-Export group permissions updated to give access to the KMS key used to encrypt the s3 export buckets.
> Encrypt standard export bucket with KMS key

- root.tf
- root_locals.tf
Requires PR: https://github.com/nationalarchives/tdr-terraform-modules/pull/268
Further IAM roles will need access to the s3 export buckets
Pass these roles as an array instead of individually
> Pass s3 export bucket access roles as array

- modules/consignment-api/ecs.tf
As part of the load testing for TDR an initial recommendation would be to increase the CPU for the Consignment API ECS task.
Increasing CPU to 1024 (1 vCPU) will potentially give the following advantages:
- Improve the overall stability of TDR when a transfer with a large number of files (1000+) is being processed with other transfers occurring in parallel. Not increasing the CPU is likely to see a degradation to judgment users when larger transfers are happening
- Improve the UI responsiveness for a transfer with a large number of files, eg user adding additional metadata etc. Some of the UI improvements and additional features being added (eg adding references) are likely to put further pressure on the API making this increase more likely to be needed regardless of trying to increase …
> Increase cpu for 'staging' and 'prod' environments

- root_keycloak.tf
- root_locals.tf
- templates/ecs_tasks/keycloak.json.tpl
Keycloak login page designs are to be changes so they can be shared between multiple services (TDR / AYR)
Use FAB to ensure new page designs are not released before completed
> Feature Access Block for shared Keycloak pages

- root_encryption.tf
- root_locals.tf
Prod has no IAM role for e2e tests which is defined as an empty string in the configurations
Trying to pass an empty string as an arn to an IAM policy causes an error
Refactor e2e test role local to array and use empty array for prod
> Fix empty string being passed as role Arn on prod

- root.tf
- root_encryption.tf
- root_locals.tf
This turns on encryption with our new customer managed KMS key for our upload bucket in s3, as well as upgrading submodules to support giving the necessary permissions to cloudfront to work with SSE-KMS.
It passes the distribution arn through to the s3 and kms modules to put in place the necessary permissions to enable use of the key from both sides.
It also passes the flag for the the encryption being enable to the cloudfront module, allowing it to use an OAC (original access control) rather than OAI (origin access identity) origin, as this is required for Cloudfront to work with SSE-KMS.
After releasing to all environments, we may want to return and remove the OAI origin altogether, but for the time being selection is driven by this new boolean.
---
Deployed to intg; verified that put …
> TDRE 54: Turn on encryption for upload bucket in intg

- root_backend_checks.tf
- root_draft_metadata.tf
- templates/api_gateway/draft_metadata.json.tpl
- templates/iam_policy/invoke_lambda_policy.json.tpl
- templates/iam_policy/lambda_av_policy.json.tpl
- templates/iam_policy/third_party_api_invocation_template.json.tpl
- templates/step_function/metadata_checks_definition.json.tpl
- Give antivirus lambda access to metadata bucket
- Create step function which calls antivirus with `metadata` scanType before calling the draft metadata validator lambda
- Update api gateway definition to call this step function instead of the lambda directly
- Create and include a role enabling the execution of the step function from api gateway
- If a virus is found, update the db by calling the consignment API directly from the step function
- Set up an eventbridge connection to the consignment API, authorised via keycloak, to enable this 
- Add a policy with the necessary permissions for this invocation and attach it to the step function role
**NB:** For now we set the `DraftMetadata` status to `Failed` if a virus is detected as it is one of the currently allowed values for a …
> TDRD 88- Evolved draft metadata step function and related infrastructure

- root.tf
For ALB logging to work the s3 bucket encryption should be set to the default encryption: 'Amazon S3-managed keys (SSE-S3)'
The existing s3 bucket has got into a state where was being encrypted by a non-existent customer managed key preventing any new ALB to log to it
The objects stored in the s3 bucket whilst using the non-existent customer managed key are still encrypted using the SSE-S3 encryption. So the bucket encryption can be reset to this
> Set ALB logging bucket encryption to default

- README.md
- root_backend_checks.tf
Notes (wip) in confluence https://national-archives.atlassian.net/wiki/spaces/DA/pages/edit-v2/497090679?draftShareId=fe0d2c15-13f0-4264-aac0-12cb3e0325ff on range of timeouts in backend checks
These two are for the overall lambda timeouts - tested these changes on staging with 10,000 files a few times.
(also a small fix in the readme)
> TDRD-147 and TDRD-148: to accommodate 10,000 files increase timeouts on lambdas in backend checks

- root_draft_metadata.tf
- root_draft_metadata_ecr.tf
This is just to see if the lambda using the ecr can be created
If it works will delete the old draft-metadata validator and replace with this
> Allow lambda to use ecr

- root_encryption.tf
We need to copy the files from the new export bucket. The bucket policy
has this role in it but the bucket is encrypted with this key and I need
permission to decrypt.
> Add dr2 role to external KMS key.

- modules/transfer-frontend/templates/draft_metadata_policy.json.tpl
The front end needs to download the draft-metadata-errors.json file
> give draft_metadata front end policy permission to getObject 

- root_backend_checks.tf
2GB files failing again today.  Suspect that miss-reading logs with AV warnings as actual failures and root cause if that timeouts in this third “file format” lamda in the map.
Seems like partial download happens in each of 5 x 1 min timeout and that therefore it sometimes works on the sixth try.  or do the three lambda share a tmp directory and it has arrived from one of the other lambda in the map that have 5 min timouts? 
Tested with these extra resources and works.  Probably need to revisit how download works and storage, will discuss next week and maybe make card. And more testing.
> TDRD-588: increase resources for file format lambda so works with 2GB file

- root_draft_metadata.tf
- templates/iam_policy/metadata_checks_policy.json.tpl
- templates/step_function/metadata_checks_definition.json.tpl
The step function will send a message to the notification topic if there is an unexpected error that has been handled in the draft-metadata-validator lambda returning statusCode 500. Although this should never happen, when the saving metadata changes have been made, it will enable the tdr team to be proactive if there are unexpected errors in prod that affect the users.
Also added slack for virus detected as we are getting false positives
> Tdrd 439 handle unexpected errors in tdr draft metadata validator lambda

- .github/scripts/logs.py
As we are now going to use the logs.py to save the `terraform plan` and `terraform apply` outputs to Cloudwatch, we will be passing the log group name from the terraform_apply.yml
Required: https://github.com/nationalarchives/tdr-github-actions/pull/84
> TDRD-259 - Get the full Log group name from terraform apply

- modules/shared-vpc/root.tf
Replaced vpc = true with domain = "vpc"
The domain argument is the current way to specify that the Elastic IP is for use in a VPC. 
overwrite attribute has been removed to remove warnings
> use latest da-terraform-modules, tdr-terraform-modules, domain = "vpc"

- root_keycloak.tf
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
> TDRD-613: increase keycloak memory on intg so compatible with CPU

- modules/shared-vpc/root.tf
- root.tf
- root_locals.tf
Terraform allowed the use of a canonical user id for the principal in an s3 bucket policy. AWS would change this to an AWS principal with corresponding account id. The terraform and resources would never look in sync. Use account id in terraform. Remove all refs to canonical users
> Fix terrform warnings plan fix

- root_s3_object_lifecycle.tf
Dirty bucket copies of records are temporary until copied to clean or quarantine buckets during backend checks
> Initial lifecyle rule for s3 dirty bucket

- templates/step_function/metadata_checks_definition.json.tpl
Removes the `CheckValidatorLambdaResult` since the The `RunValidateMetadataLambda` now properly fails if errors occur.
Example of successful step function run : https://229554778675-xtzq76ks.eu-west-2.console.aws.amazon.com/states/home?region=eu-west-2#/v2/executions/details/arn:aws:states:eu-west-2:229554778675:execution:TDRMetadataChecksIntg:ef615165-28eb-46d8-a0d6-3006df9c415c
an example of fail path:
https://229554778675-xtzq76ks.eu-west-2.console.aws.amazon.com/states/home?region=eu-west-2#/v2/executions/details/arn:aws:states:eu-west-2:229554778675:execution:TDRMetadataChecksIntg:2a8ec96f-af70-4bf4-8fa1-7ac28c11701a
> TDRD-675 - Modify RunValidateMetadataLambda

- root_locals.tf
AWS back up was tested on intg on selected resources
Revert the tags so these resources are no longer backed up
Only production resources will be backed up
> Remove backup tags on intg

- root.tf
> fix syntax for disable_inactive_judgment_users_schedule event

- root.tf
- root_locals.tf
leave env variable in so dry run can be easily run if want to see how many users might be disabled. set to false 
Implement to be scheduled to run every 30 days, and disabling users who have not user TDR for 2 years.
Phase 1: 2 years / 730 days
> remove fab dry_run
